version: 2.1

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install && npm install -g @angular/cli
      - run: npm run build
  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install && npm install -g @angular/cli
      - run: npm run lint
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - build
